### ISSUE TITLE
Diagnostics

### ISSUE THREAD

**Issue by itsdfish** [StatisticalRethinkingJulia/ParetoSmoothedImportanceSampling.jl#1]
Hi Rob,

Thank you for putting this together. I think that having a version of this in Julia will be very useful. 

Are there any plans to add diagnostics? I think they will be necessary in order to use the package outside of the examples that are known to work. [loo](https://cran.r-project.org/web/packages/loo/loo.pdf#page=40&zoom=100,133,154) and [arviz](https://arviz-devs.github.io/arviz/user_guide/pystan_refitting.html) have a few examples.

**Comment by goedman** [comment]
Hi Chris,

My current intention is to cover what is needed for the SR book. The one exception is that I will try to make version 1.0 less Stan independent.

But I had to smile, to me these are diagnostics (be it to compare models), now you want diagnostics for the diagnostics?
I have mainly looked at the vignette. Not sure how quickly I'll get to the next level `loo` docs. My new years resolution for 2021 is that in 2021 I will complete all chapters of SR. A full fledged `loo` is really a team effort.

Rob

**Comment by itsdfish** [comment]
I understand. In the next couple of weeks, I will see if I can make sense out of the code and diagnostics. If it looks like something I can do, I will submit a PR.
