### ISSUE TITLE
Change Name to ModelComparison.jl

### ISSUE THREAD

**Issue by itsdfish** [StatisticalRethinkingJulia/ParetoSmoothedImportanceSampling.jl#4]
Hi Rob,

I was wondering whether you would be amenable to changing to a more general name, such as `ModelComparison.jl`? This reflect the fact that you have multiple model comparison metrics, such as WAIC, PSILOO, and DIC.  I could easily add AIC and BIC.  I think it would benefit the ecosystem to have a central package for model comparison metrics, with an interface that does not depend on any particular package. Other packages could import and extend the methods to create a hook into the generic API. 

Does that interest you?

**Comment by goedman** [comment]
Probably the best way would be to copy the contents of PSIS, register ModelComparison(s).jl and then deprecate PSIS?

I thought a bit about this name (as Richard McElreath also calls them model comparison methods, but worried about the "Model" part in the name be to generic.

**Comment by goedman** [comment]
By the way, do you have a preference on exporting dic(), deviance() and possible future additions or would you prefer not to export them?

Recently I've not experimented with simply renaming the package on Github, maybe that works these days now a lot uses the UUID.

**Comment by itsdfish** [comment]
I think it would be good to export all of those functions because they are unlikely to conflict with other packages.

Based on a search of Discourse, it seems like your proposal is the recommended approach: [deprecate and rename a copy. ](https://discourse.julialang.org/t/renaming-packages/10433/3)

**Comment by goedman** [comment]
Ok, I'll take that route, right now it's just the 2 of us affected (I think). I'll attempt to register the new package this weekend.
